<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>FlagBrowserWpf</AssemblyName>
    <ApplicationIcon>Assets\FlagBrowser.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\values.hpp" />
    <Resource Include="Assets\FlagBrowser.ico" />
  </ItemGroup>

</Project>
